openapi: 3.1.0
info:
  title: ECOM JC-16
  description: |
    A monolith service for the ECOMJC web app
  version: 1.0.0
paths:
  /v1/products:
    post:
      summary: Add a new product for merchant's shop
      responses:
        201:
          description: Product successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  product_id:
                    type: string
    get:
      summary: Get all products
      responses:
        201:
          description: Products successfully returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    items:
                        type: object,
                        properties:
                            id:
                                type: string
                            shop_id:
                                type: string
                            category_id:
                                type: string
                            category_name:
                                type: string
                            spec_id:
                                type: string
                            name:
                                type: string
                            description:
                                type: string
                            price:
                                type: int
                            stock:
                                type: int
                            weight:
                                type: int
                            amount_sold:
                                type: int
                            created_at:
                                type: string
                            updated_at:
                                type: string
                            is_deleted:
                                type: boolean